version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp
permissions:
  - object: /home/ec2-user/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location:  start_preview.sh
      timeout: 60
      runas: ec2-user
      waitAfterCompletion: 0
      ignoreErrors: false
