version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.14.2
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - zip -r app.zip dist/

artifacts:
  files:
    - app.zip
